---
- name: Check Strong Password Policies Status
  hosts: all
  become: yes
  become_method: runas
  become_user: SYSTEM
  tasks:
    - name: Get Password Policy Settings
      win_password_policy_info:
      register: password_policy

    - name: Display Password Policy Status
      debug:
        msg: |
          Minimum Password Length: {{ password_policy.minimum_password_length }}
          Password Complexity Enabled: {{ password_policy.password_complexity }}
          Maximum Password Age: {{ password_policy.maximum_password_age }} days
          Password History Size: {{ password_policy.password_history_size }}

    - name: Get Account Lockout Policy Settings
      win_account_lockout_policy_info:
      register: lockout_policy

    - name: Display Account Lockout Policy Status
      debug:
        msg: |
          Lockout Threshold: {{ lockout_policy.lockout_threshold }}
          Lockout Duration: {{ lockout_policy.lockout_duration }} minutes
          Lockout Window: {{ lockout_policy.lockout_window }} minutes

