---
- name: Check if Audit Logging is Enabled
  hosts: all
  gather_facts: no
  tasks:

    - name: Check Audit Logging status
      win_shell: |
        Get-AuditPolicy | Where-Object { $_.Category -eq 'Logon/Logoff' } | Select-Object -ExpandProperty Success
      register: audit_log_status

    - name: Display Audit Logging status
      debug:
        msg: >
          Audit Logging is {{
          'enabled' if audit_log_status.stdout.strip() == 'Success' else 'disabled'
          }}.

