---
- name: Check Windows Firewall Status
  hosts: all
  become: yes
  become_method: runas
  become_user: SYSTEM
  tasks:
    - name: Check if Windows Firewall is enabled for all profiles using PowerShell
      win_shell: |
        (Get-NetFirewallProfile -Profile Domain,Private,Public).Enabled
      register: firewall_status

    - name: Print firewall_status for debugging
      debug:
        var: firewall_status

    - name: Display Firewall Status - Enabled
      debug:
        msg: "Windows Firewall is enabled for one or more profiles."
      when: firewall_status.stdout.strip() != 'False False False'

    - name: Display Firewall Status - Disabled
      debug:
        msg: "Windows Firewall is completely disabled for all profiles."
      when: firewall_status.stdout.strip() == 'False False False'

