---
- name: Enable Windows Firewall
  hosts: windows
  tasks:
    - name: Enable all firewalls on Windows
      win_shell: |
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
