---
- name: Deactivate Strong Password Policies
  hosts: all
  become: yes
  become_method: runas
  become_user: SYSTEM
  tasks:
    - name: Reset Minimum Password Length to Default (7)
      win_password_policy:
        minimum_password_length: 7

    - name: Disable Password Complexity Requirements
      win_password_policy:
        password_complexity: disabled

    - name: Set Password Expiration to Default (42 days)
      win_password_policy:
        maximum_password_age: 42

    - name: Set Password History Size to Default (0)
      win_password_policy:
        password_history_size: 0

    - name: Disable Account Lockout Policy
      win_account_lockout_policy:
        lockout_threshold: 0
        lockout_duration: 0
        lockout_window: 0

