---
- name: Disable Windows Defender and Remove Scheduled Daily Scan
  hosts: all
  become: yes
  become_method: runas
  become_user: SYSTEM
  tasks:
    - name: Disable Windows Defender feature using DISM (for client editions)
      win_shell: |
        DISM /Online /Disable-Feature /FeatureName:Windows-Defender-ApplicationGuard /NoRestart
      args:
        executable: cmd
      register: defender_dism_output
      failed_when: "'Error' in defender_dism_output.stdout"
      ignore_errors: yes

    - name: Display DISM output for debugging
      debug:
        var: defender_dism_output

    - name: Disable Windows Defender Real-Time Protection
      win_shell: |
        Set-MpPreference -DisableRealtimeMonitoring $true

    - name: Remove the scheduled daily full scan task
      win_shell: |
        Unregister-ScheduledTask -TaskName "DailyWindowsDefenderScan" -Confirm:$false
      ignore_errors: yes

