---
- name: Disable Windows Firewall
  hosts: all
  become: yes
  become_method: runas
  become_user: SYSTEM
  tasks:
    - name: Disable Windows Firewall for Domain, Private, and Public profiles
      win_shell: |
        Set-NetFirewallProfile -Profile Domain,Private,Public -Enabled False
