---
- name: Disable Autorun in Windows
  hosts: windows
  tasks:
    - name: Disable Autorun via registry
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
        name: NoDriveTypeAutoRun
        data: 255
        type: dword
      become: true
      become_method: runas
      become_user: SYSTEM
