---
- name: Enforce USB Port Restrictions
  hosts: all
  become: yes
  become_method: runas
  become_user: SYSTEM
  tasks:
    - name: Disable USB Storage via Registry
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR
        name: Start
        data: 4
        type: dword

    - name: Restrict Removable Media Access to Authorized Users
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\RemovableStorageDevices
        name: "Deny_All"
        state: present

    - name: Detect system language
      win_shell: |
        [System.Globalization.CultureInfo]::InstalledUICulture.Name
      register: lang

    - name: Set audit category based on system language
      set_fact:
        audit_category: "{{ 'Removable Storage' if lang.stdout.startswith('en') else 'Stockage amovible' }}"

    - name: Enable Auditing for USB Port Access Attempts
      win_shell: |
        auditpol /set /subcategory:"{{ audit_category }}" /success:enable /failure:enable
      args:
        executable: PowerShell
