- name: Enable AutoRun and AutoPlay Features
  hosts: all
  become: yes
  become_method: runas
  become_user: SYSTEM
  tasks:
    - name: Enable AutoRun via Registry
      win_shell: |
        reg add "HKLM\Software\Policies\Microsoft\Windows\System" /v "DisableAutoRun" /t REG_DWORD /d 0 /f

    - name: Enable AutoPlay via Registry
      win_shell: |
        reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" /v "NoDriveTypeAutoRun" /t REG_DWORD /d 91 /f

    - name: Disable Auditing for AutoRun/AutoPlay Attempts
      win_shell: |
        auditpol /set /subcategory:"Other System Events" /success:disable /failure:disable

