---
- name: Enforce Strong Password Policies
  hosts: all
  become: yes
  become_method: runas
  tasks:
    - name: Set Minimum Password Length
      win_password_policy:
        minimum_password_length: 12

    - name: Set Password Complexity Requirements
      win_password_policy:
        password_complexity: enabled

    - name: Set Password Expiration (90 days)
      win_password_policy:
        maximum_password_age: 90

    - name: Set Password History (24 previous passwords)
      win_password_policy:
        password_history_size: 24

    - name: Enable Account Lockout Policy (5 failed attempts)
      win_account_lockout_policy:
        lockout_threshold: 5
        lockout_duration: 15
        lockout_window: 15

